### PR TITLE
Geolite2

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Migration to GeoLiteCity2 DB

### CODE REVIEW

**Comment by andreslucena** [comment]
This PR is compatible with #230 ? Or what is the final PR?

**Comment by deivid-rodriguez** [comment]
@andreslucena You're right, the previous PR's were confusing... I changed them to be more clear. The idea is to follow this steps in order:

* [ ] Merge #230, so we make the `nolotiro:download_maxmind_db` task available in production. No big deal, really, the commands could be run manually but I think it's nice to have a rake task to do it, and it simplifies things in a few places (`bin/bootstrap.sh`, `.travis.yml`).
* [ ] Deploy #230.
* [ ] Download the new DB in production, using `RAILS_ENV=production bin/rake nolotiro:download_maxmind_db`.
* [ ] Merge this PR.
* [ ] Deploy this PR.

**Comment by deivid-rodriguez** [comment]
Note that the build is currently failing because, indeed, this PR depends on #230.

**Comment by deivid-rodriguez** [comment]
Probado en staging, parece que la cosa ha mejorado un pokito! :wink: 

captura de pantalla de 2016-06-01 19 42 20

**Pull request merged**
